CREATE TABLE CART
(
    ID INTEGER PRIMARY KEY NOT NULL,
    CUSTOMER_ID INTEGER NOT NULL,
    NAME VARCHAR(50) NOT NULL,
	FOREIGN KEY ( CUSTOMER_ID ) REFERENCES CUSTOMER ( ID )
);
CREATE TABLE CART_ITEM
(
    CART_ID INTEGER NOT NULL,
    PRODUCT_ID INTEGER NOT NULL,
    ITEM_QTY INTEGER NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    PRIMARY KEY ( CART_ID, PRODUCT_ID ),
	FOREIGN KEY ( CART_ID ) REFERENCES CART ( ID ),
	FOREIGN KEY ( PRODUCT_ID ) REFERENCES PRODUCT ( ID )
);
CREATE TABLE CATEGORY
(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION CLOB
);
CREATE TABLE CUSTOMER
(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    REGISTRATION_DATE DATE DEFAULT CURRENT_DATE() NOT NULL
);
CREATE TABLE PRODUCT
(
    ID INTEGER PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION CLOB NOT NULL,
    PRICE DECIMAL(5,2) NOT NULL,
    STOCK_QTY INTEGER NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP() NOT NULL,
    CATEGORY_ID INTEGER NOT NULL,
	FOREIGN KEY ( CATEGORY_ID ) REFERENCES CATEGORY ( ID )
);
