services:
  web:
    container_name: web
    build: 
      context: .
      #target: builder
    stop_signal: SIGINT
    ports:
      - "5000:5000"
    volumes:
      - ./vol:/mnt/app
    environment:
      - FLASK_ENV=development
