--SNOWFLAKE
SELECT C.TABLE_SCHEMA, C.TABLE_NAME, C.COLUMN_NAME, C.ORDINAL_POSITION, C.COLUMN_DEFAULT, C.IS_NULLABLE, C.DATA_TYPE, 
	COALESCE(CONCAT(C.NUMERIC_PRECISION, ',', C.NUMERIC_SCALE), CAST(C.CHARACTER_MAXIMUM_LENGTH AS VARCHAR)) AS COLUMN_SIZE, 
	--IS_PRIMARY_KEY, 
	CASE
		WHEN C.IDENTITY_GENERATION IS NOT NULL THEN CONCAT('IDENTITY(', C.IDENTITY_START, ',', C.IDENTITY_INCREMENT, ')') 
		ELSE NULL
	END AS IDENTITY_DEFINITION,
	--IS_UNIQUE, COULUMN_CHECK, REFERENCE_KEY 
FROM INFORMATION_SCHEMA."COLUMNS" C
WHERE TABLE_CATALOG = <DBNAME>
AND TABLE_SCHEMA = <SCHEMA_NAME>
ORDER BY 1, 2, 4

--mssql
SELECT C.TABLE_SCHEMA, C.TABLE_NAME, C.COLUMN_NAME, C.ORDINAL_POSITION, C.COLUMN_DEFAULT, C.IS_NULLABLE, C.DATA_TYPE, 
	COALESCE(CONCAT(C.NUMERIC_PRECISION, ',', C.NUMERIC_SCALE), CAST(C.CHARACTER_MAXIMUM_LENGTH AS VARCHAR)) AS COLUMN_SIZE, 
	--IS_PRIMARY_KEY, 
	CASE
		WHEN I.IS_IDENTITY = 1 THEN CONCAT('IDENTITY(', CAST(I.SEED_VALUE AS VARCHAR), ',', CAST(I.INCREMENT_VALUE AS VARCHAR), ')') 
		ELSE NULL
	END AS IDENTITY_DEFINITION
	--IS_UNIQUE, COULUMN_CHECK, REFERENCE_KEY 
FROM INFORMATION_SCHEMA."COLUMNS" C
LEFT OUTER JOIN sys.identity_columns I
ON C.COLUMN_NAME = I.NAME
--WHERE TABLE_CATALOG = <DBNAME>
--AND TABLE_SCHEMA = <SCHEMA_NAME>
ORDER BY 1, 2, 4
